---
- name: Clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default( ansible_env.HOME ~ '/.oh-my-zsh/custom', True) }}/themes/powerlevel10k"
    depth: 1

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default( ansible_env.HOME ~ '/.oh-my-zsh/custom', True) }}/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default( ansible_env.HOME ~ '/.oh-my-zsh/custom', True) }}/plugins/zsh-autosuggestions"
    depth: 1